In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('iris.csv')

In [18]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Checking the number of null values

In [4]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Printing the number of each type of flower

In [7]:
for i in df['variety'].value_counts():
    print(i,end =' ')

50 50 50

Printing the data of the flower 'Iris-Virginica',where petal-length>1.5

In [11]:
df[(df['variety']=="Virginica")&(df["petal.length"]>1.5)]

     sepal.length  sepal.width  petal.length  petal.width    variety
100           6.3          3.3           6.0          2.5  Virginica
101           5.8          2.7           5.1          1.9  Virginica
102           7.1          3.0           5.9          2.1  Virginica
103           6.3          2.9           5.6          1.8  Virginica
104           6.5          3.0           5.8          2.2  Virginica
105           7.6          3.0           6.6          2.1  Virginica
106           4.9          2.5           4.5          1.7  Virginica
107           7.3          2.9           6.3          1.8  Virginica
108           6.7          2.5           5.8          1.8  Virginica
109           7.2          3.6           6.1          2.5  Virginica
110           6.5          3.2           5.1          2.0  Virginica
111           6.4          2.7           5.3          1.9  Virginica
112           6.8          3.0           5.5          2.1  Virginica
113           5.7          2.5           5.0          2.0  Virginica
114           5.8          2.8           5.1          2.4  Virginica
115           6.4          3.2           5.3          2.3  Virginica
116           6.5          3.0           5.5          1.8  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica
119           6.0          2.2           5.0          1.5  Virginica
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

Printing the minimum,maximum and average value of the feature for each kind of flower

In [15]:
print(df[df.variety=="Setosa"].min())
print(df[df.variety=="Setosa"].max())
print(df[df.variety=="Setosa"].mean())

sepal.length       4.3
sepal.width        2.3
petal.length         1
petal.width        0.1
variety         Setosa
dtype: object
sepal.length       5.8
sepal.width        4.4
petal.length       1.9
petal.width        0.6
variety         Setosa
dtype: object
sepal.length    5.006
sepal.width     3.428
petal.length    1.462
petal.width     0.246
dtype: float64

In [16]:
print(df[df.variety=="Versicolor"].min())
print(df[df.variety=="Versicolor"].max())
print(df[df.variety=="Versicolor"].mean())

sepal.length           4.9
sepal.width              2
petal.length             3
petal.width              1
variety         Versicolor
dtype: object
sepal.length             7
sepal.width            3.4
petal.length           5.1
petal.width            1.8
variety         Versicolor
dtype: object
sepal.length    5.936
sepal.width     2.770
petal.length    4.260
petal.width     1.326
dtype: float64

In [17]:
print(df[df.variety=="Virginica"].min())
print(df[df.variety=="Virginica"].max())
print(df[df.variety=="Virginica"].mean())

sepal.length          4.9
sepal.width           2.2
petal.length          4.5
petal.width           1.4
variety         Virginica
dtype: object
sepal.length          7.9
sepal.width           3.8
petal.length          6.9
petal.width           2.5
variety         Virginica
dtype: object
sepal.length    6.588
sepal.width     2.974
petal.length    5.552
petal.width     2.026
dtype: float64

In [20]:
df1=pd.read_csv('terrorismData.csv')

In [21]:
df1.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [23]:
df1.drop(df1[df1["Day"]==0].index,inplace=True)
df1.drop(df1[df1["Month"]==0].index,inplace=True)

In [25]:
ct = df1['Country'].value_counts()
mc = ct.index[0]
mt = ct.values[0]
yt = df1[df1['Country'] == mc]['Year'].value_counts()
my = yt.index[0]
mty = yt.values[0]
print(mc," ",mt," ",mty)

Iraq   24616   3933